project_id = "svelte-app-demo-455307"
region = "asia-northeast1"
artifact_registry_repository_name = "svelte-app-repo"
artifact_registry_image_name = "svelte-app"
cloud_run_service_name = "svelte-sample"
cloudsql_instance_name = "svelte-app-demo-db"
cloudsql_database_name = "demo"
terraform_state_bucket_name = "svelte-app-demo-455307-terraform"
