name: ci-cd
# mainにマージされたら、imageを作成しArtifactRegistryにpushする
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'app/**'
      - 'Dockerfile'

permissions:
  contents: read
  id-token: write

jobs:
  check-pr-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged

  deploy-to-cloud-run:
    needs: check-pr-merged
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Actionsにリポジトリのソースを読みこめるようにする

    - name: Authenticate to Google Cloud # GitHub ActionsでGCPにアクセスするための認証
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_FOR_APP}} # github actionsが使用するサービスアカウント

    - name: Set up Cloud SDK # GitHub ActionsでGCPにアクセスするためのSDKをセットアップ
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker authentication for Artifact Registry # Artifact Registryにアクセスするための認証
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

    # TODO: 最新のimage以外削除する（あれば）

    - name: Build and push Docker image # Dockerイメージをビルドし、Artifact Registryにpush
      uses: docker/build-push-action@v4
      with:
        context: app/
        push: true
        tags: |
          asia-northeast1-docker.pkg.dev/svelte-app-demo-455307/svelte-app-repo/svelte-app${{ github.event.pull_request.merge_commit_sha }}
          asia-northeast1-docker.pkg.dev/svelte-app-demo-455307/svelte-app-repo/svelte-app:latest

    - name: Deploy to Cloud Run # Cloud Runにデプロイ
      run: |
        gcloud run deploy svelte-sample \
          --image=asia-northeast1-docker.pkg.dev/svelte-app-demo-455307/svelte-app-repo/svelte-app${{ github.event.pull_request.merge_commit_sha }} \
          --region=asia-northeast1 \
          --platform=managed \
          --port=8080 \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=1 \
          --min-instances=0 \
          --allow-unauthenticated \
          --service-account=cloud-run-sa@svelte-app-demo-455307.iam.gserviceaccount.com \
          --add-cloudsql-instances=svelte-app-demo-455307:asia-northeast1:svelte-app-demo-db \
          --set-secrets=DATABASE_URL=DATABASE_URL:latest
    
    - name: Run migrations if needed
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q "app/prisma/migrations/"; then
          gcloud run jobs execute db-migration-job \
            --region=asia-northeast1 \
            --wait
        else
          echo "マイグレーションの変更はありません。スキップします。"
        fi
